### ISSUE TITLE
Addon is not compatible with WoWUp

### ISSUE THREAD

**Issue by KevinTyrrell** [scarecr0w12/CensusPlusWotlk#10]
On the [releases](https://github.com/scarecr0w12/CensusPlusWotlk/releases) page, a release is required which contains a `.zip` file whose filename ends with `-bc`, `-bcc`, or `-wrath`. For example, [this release from LeatrixMaps](https://github.com/leatrix/leatrix-maps-wrath/releases/tag/3.0.00) has a release named `Leatrix_Maps-3.0.00-wrath.zip`. 

CEnsusPlusWotlk should create a release which contains a file like the following:

`CensusPlusWotlk-wotlk.zip`

![image](https://user-images.githubusercontent.com/12791400/187576426-6a5453a7-5ed4-418f-8452-9a5d2a5f499a.png)

**Comment by scarecr0w12** [comment]
It should be getting picked up via wow interface since its listed there now as well from what i understand, but i'll put out another release for that instance.

**Comment by scarecr0w12** [comment]
This should now be showing correctly in wowup

**Comment by KevinTyrrell** [comment]
Strange, it still gives me an error but by the looks of it you've done everything right. It does allow me to install it which is better than before. Perhaps it is `-wotlk` ? Not completely sure.

**Comment by scarecr0w12** [comment]
> Strange, it still gives me an error but by the looks of it you've done everything right. It does allow me to install it which is better than before. Perhaps it is `-wotlk` ? Not completely sure.
> 
> ![image](https://user-images.githubusercontent.com/12791400/188370417-8f23968a-a0e2-4e32-aaed-e6c68c59d6c2.png)

I would just use the wowinterface source for wowup, its up there and loading in wowup for me
