### ISSUE TITLE
Spanish localization for blood elf is missing

### ISSUE THREAD

**Issue by HonzoNebro** [scarecr0w12/CensusPlusWotlk#13]
**Describe the bug**
Spanish localization for blood elf is missing

**To Reproduce**
Use the addon while the game is in spanish

**Expected behavior**
It finds blood elf players

I added

```
	CENSUSPLUS_BLOODELF = "Elfo de sangre";
	CENSUSPlusFemale["Elfo de sangre"] = "Elfo de sangre";
```

 to my local.lua to fix it. I didn't open a pull request, I couldn't find the file on the repo

![imagen](https://user-images.githubusercontent.com/5500663/189606237-aa93489f-5042-458b-83eb-550d0f2ffffb.png)

**Comment by scarecr0w12** [comment]
This is fixed in newest version
