### ISSUE TITLE
German "ORC" does not count

### ISSUE THREAD

**Issue by NVO88** [scarecr0w12/CensusPlusWotlk#15]
**Describe the bug**
![image](https://user-images.githubusercontent.com/82704214/190671135-1d5a1f14-c35a-4a30-9608-7d6a9ade2489.png)
![image](https://user-images.githubusercontent.com/82704214/190671323-12d8236f-0b7f-453a-873a-34d2fb3099bd.png)

See the Image
+
**To Reproduce**
Just auto search, the german "ORK" was changed by blizzard to "orc"

**Expected behavior**
Orcs should be searched instead of ORKs

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NVO88** [comment]
Change the following:
CensusPlusWotlk\locales\localization.lua (1 Treffer)
	line 85: 	CENSUSPLUS_ORC = "Ork";

after the it will work again

**Comment by scarecr0w12** [comment]
Just to confirm, based on your screenshot, it appears there is Orc and Orcin, Am i to assume these are Male/Female variations? I just want to make sure i get this in properly. 

Also, i added all translations to Curseforge for people to submit changes if you want to take a look there :D

**Comment by NVO88** [comment]
Hi yes, i found out, that it is only the visual part upon the statistics, i've rewrote that part as mentioned to let it work correctly 
CensusPlusWotlk\locales\localization.lua (1 Treffer)
line 85: CENSUSPLUS_ORC = "Ork";

![image](https://user-images.githubusercontent.com/82704214/190730110-7c4db666-8849-4fc8-a265-d5bb8e88cb0c.png)

**Comment by NVO88** [comment]
CENSUSPLUS_ORC = "Orc";
