### ISSUE TITLE
Invalid anchor point info.

### ISSUE THREAD

**Issue by endomorphine** [scarecr0w12/CensusPlusWotlk#20]
**Describe the bug**
Lua error every time I login and using /reload. While I don't really use census info in guild window, I would prefer to get rid off this error.

**To Reproduce**
1. Install CensusPlusWotlk-v0.9.16-wrath.zip version
2. Login on character
3. Now you see Lua Error.

**Expected behavior**
No error.

**World of Warcraft Information:**
 - WoW Version: 3.4.0
 - Addon Version: CensusPlusWotlk-v0.9.16-wrath.zip
 - Other Addons used: many of them, tried to turn off guild-related, no luck. Seems like this error related to Census itself

**Additional context**
I will happily help test fixes if you want

**Comment by scarecr0w12** [comment]
Fixed in current version
